- title: "Automatisation & Orchestration"
  text: "Libérez vos équipes des tâches répétitives. J’automatise et orchestre vos processus pour garantir fluidité, fiabilité et réactivité, avec alertes en temps réel en cas d’incident."
  badges: ["CI/CD", "Scheduling", "Monitoring"]

- title: "Migration & Modernisation"
  text: "Sécurisez vos transitions. J’assure la continuité de vos données et la conformité de vos systèmes lors de changements d’ERP, d’outils métiers ou de plateformes."
  badges: ["Migration", "Sécurité", "Conformité"]

- title: "Intégration & Interopérabilité"
  text: "Un seul système, une vérité unique. J’unifie vos applications pour éliminer les doublons, fiabiliser vos référentiels et valoriser vos données à travers toute l’organisation."
  badges: ["API", "Connecteurs", "Interopérabilité"]

- title: "Data Quality & Performance"
  text: "Des données fiables, des décisions rapides. J’améliore la qualité et la performance de vos flux et dashboards pour garantir confiance et efficacité opérationnelle."
  badges: ["Qualité", "Observabilité", "Optimisation"]
