- title: "Automatisation & Orchestration"
  text: "Évitez les tâches manuelles chronophages. Je conçois des orchestrations fiables : planification des traitements, enchaînement des jobs, gestion des dépendances et notifications en cas d’incident."
  badges: ["CI/CD", "Scheduling", "Monitoring", "Alerte & suivi"]

- title: "Migration de systèmes"
  text: "Vous souhaitez changer d’ERP, de site web ou de solution métier ? Une migration réussie, c’est préserver l’historique, sécuriser vos données et mettre en valeur ce qui a du sens pour votre entreprise, sans perdre la moindre information."
  badges: ["Migration", "Historique", "ETL/ESB", "Mise en conformité"]

- title: "Interconnexion d’applications"
  text: "Marre d’avoir des doublons de données dans trois logiciels différents ? Faites-les communiquer entre eux ! Une donnée unique répercutée sur l’ensemble de votre système, c’est l’assurance d’un référentiel propre et sans erreur."
  badges: ["Interconnexion", "Valorisation", "API/Connecteurs", "Interopérabilité"]

- title: "Qualité & Performance des données"
  text: "Vos dashboards mettent trop de temps à se charger ? Vos équipes doutent parfois de la fiabilité des chiffres ? Un suivi de la qualité et des performances assure des données justes, exploitables et disponibles au bon moment."
  badges: ["Observabilité", "Tests automatisés", "SLAs", "Optimisation"]
